#%RAML 1.0
title: Assessments Process API

description: As a user of Caliber, you would be able to get average assessment scores by category or assessment type for all time.

types:
  grades: !include DataTypes/assessmentDataType.raml
  aggregatedCategory: !include DataTypes/aggregatedCategoryDataType.raml
  aggregatedType: !include DataTypes/aggregatedTypeDataType.raml

/category/average:
  get:
    displayName: Get Aggregated Assessment Score By Category
    responses:
      200:
        body:
          application/json:
            type: aggregatedCategory[]
            examples:
              output: !include Examples/aggregatedCategoryExample.raml

/type/average:
  get:
    displayName: Get Aggregated Assessment Score By Type
    responses:
      200:
        body:
          application/json:
            type: aggregatedType[]
            examples:
              output: !include Examples/aggregatedAssessmentExample.raml
